// Player 타입 정의
export type Player = {
  id: string
  name: string
  profileImage?: string
  position: string
  level: string
  lastActive: string
  bio: string
}

// mock player 데이터
export const mockPlayers: Player[] = [
  {
    id: 'user1',
    name: 'Yoo', // mockData.users[0]와 일치
    profileImage: '/images/profile1.png',
    position: 'SF', // FORWARD → SF로 변환
    level: 'A',
    lastActive: '2일 전',
    bio: 'TeamUp is good!', // mockData.users[0]의 statusMsg와 일치
  },
  {
    id: 'user2',
    name: '이광진',
    profileImage: '/images/profile2.png',
    position: 'SF',
    level: 'B+',
    lastActive: '5일 전',
    bio: '높은 점프력과 리바운드 능력이 뛰어납니다.',
  },
  {
    id: 'user3',
    name: '박강남',
    profileImage: '/images/profile3.png',
    position: 'C',
    level: 'A+',
    lastActive: '1주 전',
    bio: '팀의 골밑을 책임지는 든든한 센터.',
  },
  {
    id: 'user4',
    name: '최민수',
    profileImage: '/images/profile4.png',
    position: 'PG',
    level: 'A',
    lastActive: '3일 전',
    bio: '빠른 패스와 게임 리딩이 특기입니다.',
  },
  {
    id: 'user5',
    name: '정태영',
    profileImage: '/images/profile5.png',
    position: 'SG',
    level: 'B+',
    lastActive: '1일 전',
    bio: '정확한 3점슛으로 팀을 이끕니다.',
  },
  {
    id: 'user6',
    name: '김도현',
    profileImage: '/images/profile6.png',
    position: 'PF',
    level: 'A-',
    lastActive: '4일 전',
    bio: '강력한 인사이드 플레이와 리바운드.',
  },
]

// 팀원 정보 (팀 상세 페이지용)
export interface TeamMemberInfo {
  id: string
  name: string
  email: string
  position: 'GUARD' | 'FORWARD' | 'CENTER'
  playStyle?: 'SLASHER' | 'SHOOTER' | 'DEFENDER' | 'PASSER'
  height?: number
  isLeader: boolean
}

// 세종 born 팀의 팀원 목록 (mockMyTeam용)
export const mockMyTeamMembers: TeamMemberInfo[] = [
  {
    id: 'user1',
    name: 'Yoo',
    email: 'Yoo@gmail.com',
    position: 'FORWARD',
    playStyle: 'SHOOTER',
    height: 178,
    isLeader: true,
  },
  {
    id: 'user2',
    name: '이광진',
    email: 'kwangjin@example.com',
    position: 'FORWARD',
    playStyle: 'SLASHER',
    height: 185,
    isLeader: false,
  },
  {
    id: 'user3',
    name: '박강남',
    email: 'kangnam@example.com',
    position: 'CENTER',
    playStyle: 'DEFENDER',
    height: 195,
    isLeader: false,
  },
  {
    id: 'user4',
    name: '최민수',
    email: 'minsu@example.com',
    position: 'GUARD',
    playStyle: 'PASSER',
    height: 175,
    isLeader: false,
  },
  {
    id: 'user5',
    name: '정태영',
    email: 'taeyoung@example.com',
    position: 'GUARD',
    playStyle: 'SHOOTER',
    height: 180,
    isLeader: false,
  },
  {
    id: 'user6',
    name: '김도현',
    email: 'dohyun@example.com',
    position: 'FORWARD',
    playStyle: 'SLASHER',
    height: 188,
    isLeader: false,
  },
]

// 다른 팀의 팀원 목록 (팀별로 정의)
export const mockTeamMembers: Record<string, TeamMemberInfo[]> = {
  // 세종 Warriors (id: '2', captainId: 'user2')
  '2': [
    {
      id: 'user2',
      name: '이광진',
      email: 'kwangjin@example.com',
      position: 'FORWARD',
      playStyle: 'SLASHER',
      height: 185,
      isLeader: true,
    },
    {
      id: 'user7',
      name: '장현우',
      email: 'hyunwoo@example.com',
      position: 'GUARD',
      playStyle: 'PASSER',
      height: 172,
      isLeader: false,
    },
    {
      id: 'user8',
      name: '오준호',
      email: 'junho@example.com',
      position: 'CENTER',
      playStyle: 'DEFENDER',
      height: 192,
      isLeader: false,
    },
    {
      id: 'user9',
      name: '윤성민',
      email: 'sungmin@example.com',
      position: 'GUARD',
      playStyle: 'SHOOTER',
      height: 178,
      isLeader: false,
    },
    {
      id: 'user10',
      name: '한지훈',
      email: 'jihun@example.com',
      position: 'FORWARD',
      playStyle: 'SLASHER',
      height: 183,
      isLeader: false,
    },
    {
      id: 'user11',
      name: '강태현',
      email: 'taehyun@example.com',
      position: 'CENTER',
      playStyle: 'DEFENDER',
      height: 190,
      isLeader: false,
    },
    {
      id: 'user12',
      name: '조민석',
      email: 'minseok@example.com',
      position: 'FORWARD',
      playStyle: 'SHOOTER',
      height: 181,
      isLeader: false,
    },
  ],
  // 관악 Hoops (id: '4', captainId: 'user4')
  '4': [
    {
      id: 'user4',
      name: '최민수',
      email: 'minsu@example.com',
      position: 'GUARD',
      playStyle: 'PASSER',
      height: 175,
      isLeader: true,
    },
    {
      id: 'user13',
      name: '송지원',
      email: 'jiwon@example.com',
      position: 'GUARD',
      playStyle: 'SHOOTER',
      height: 177,
      isLeader: false,
    },
    {
      id: 'user14',
      name: '임동혁',
      email: 'donghyuk@example.com',
      position: 'FORWARD',
      playStyle: 'SLASHER',
      height: 186,
      isLeader: false,
    },
    {
      id: 'user15',
      name: '배성호',
      email: 'sungho@example.com',
      position: 'CENTER',
      playStyle: 'DEFENDER',
      height: 194,
      isLeader: false,
    },
    {
      id: 'user16',
      name: '류건우',
      email: 'geonwoo@example.com',
      position: 'FORWARD',
      playStyle: 'SHOOTER',
      height: 182,
      isLeader: false,
    },
    {
      id: 'user17',
      name: '신우진',
      email: 'woojin@example.com',
      position: 'GUARD',
      playStyle: 'PASSER',
      height: 174,
      isLeader: false,
    },
  ],
  // 송파 Dunk (id: '5', captainId: 'user5')
  '5': [
    {
      id: 'user5',
      name: '정태영',
      email: 'taeyoung@example.com',
      position: 'GUARD',
      playStyle: 'SHOOTER',
      height: 180,
      isLeader: true,
    },
    {
      id: 'user18',
      name: '홍준서',
      email: 'junseo@example.com',
      position: 'GUARD',
      playStyle: 'PASSER',
      height: 176,
      isLeader: false,
    },
    {
      id: 'user19',
      name: '문재현',
      email: 'jaehyun@example.com',
      position: 'FORWARD',
      playStyle: 'SLASHER',
      height: 184,
      isLeader: false,
    },
    {
      id: 'user20',
      name: '양준혁',
      email: 'junhyuk@example.com',
      position: 'CENTER',
      playStyle: 'DEFENDER',
      height: 196,
      isLeader: false,
    },
    {
      id: 'user21',
      name: '노민규',
      email: 'mingyu@example.com',
      position: 'FORWARD',
      playStyle: 'SHOOTER',
      height: 179,
      isLeader: false,
    },
    {
      id: 'user22',
      name: '구본영',
      email: 'bonyoung@example.com',
      position: 'GUARD',
      playStyle: 'SLASHER',
      height: 173,
      isLeader: false,
    },
    {
      id: 'user23',
      name: '서도현',
      email: 'dohyun2@example.com',
      position: 'CENTER',
      playStyle: 'DEFENDER',
      height: 191,
      isLeader: false,
    },
    {
      id: 'user24',
      name: '전승우',
      email: 'seungwoo@example.com',
      position: 'FORWARD',
      playStyle: 'PASSER',
      height: 187,
      isLeader: false,
    },
  ],
}

// id로 player 조회
export function getPlayerById(id: string): Player | undefined {
  return mockPlayers.find((p) => p.id === id)
}
import type { Team } from '@/types'

// 모집 중인 팀 (팀원 모집 - 5명 미만)
export const mockJoinTeams: Team[] = [
  {
    id: '3',
    name: '강남 Thunder',
    shortName: 'GT',
    region: '강남구 역삼',
    level: 'A+',
    matchScore: 92,
    memberCount: 4,
    maxMembers: 10,
    isOfficial: false,
    captainId: 'user3',
    description: '1명 모집 중! PG/SG 포지션 우대합니다.',
    totalGames: 25,
    aiReports: 20,
    activeDays: 80,
  },
  {
    id: '6',
    name: '마포 Ballers',
    shortName: 'MB',
    region: '마포구 합정',
    level: 'B+',
    matchScore: 88,
    memberCount: 3,
    maxMembers: 10,
    isOfficial: false,
    captainId: 'user6',
    description: '2명 모집 중! 평일 저녁에 활동합니다.',
    totalGames: 12,
    aiReports: 10,
    activeDays: 30,
  },
  {
    id: '7',
    name: '용산 Hawks',
    shortName: 'YH',
    region: '용산구 이촌',
    level: 'A',
    matchScore: 85,
    memberCount: 2,
    maxMembers: 10,
    isOfficial: false,
    captainId: 'user7',
    description: 'SF/PF 포지션 모집 중입니다!',
    totalGames: 18,
    aiReports: 15,
    activeDays: 50,
  },
  {
    id: '8',
    name: '성북 Wolves',
    shortName: 'SW',
    region: '성북구 정릉',
    level: 'B',
    matchScore: 82,
    memberCount: 4,
    maxMembers: 10,
    isOfficial: false,
    captainId: 'user8',
    description: '초보 환영! 편하게 농구 즐기실 분 모집합니다.',
    totalGames: 8,
    aiReports: 6,
    activeDays: 20,
  },
]

// 정식 팀 (매칭용 - 5명 이상)
export const mockMatchTeams: Team[] = [
  {
    id: '2',
    name: '세종 Warriors',
    shortName: 'SW',
    region: '광진구 능동',
    teamDna: 'WARRIORS',
    level: 'A',
    matchScore: 95,
    memberCount: 7,
    maxMembers: 10,
    isOfficial: true,
    captainId: 'user2',
    description: '주말 오후에 활동하는 친목 위주 팀입니다.',
    totalGames: 20,
    aiReports: 15,
    activeDays: 60,
  },
  {
    id: '4',
    name: '관악 Hoops',
    shortName: 'GH',
    region: '관악구 신림',
    teamDna: 'SPURS',
    level: 'B+',
    matchScore: 88,
    memberCount: 6,
    maxMembers: 10,
    isOfficial: true,
    captainId: 'user4',
    description: '주 2회 정기 경기를 진행합니다.',
    totalGames: 15,
    aiReports: 12,
    activeDays: 40,
  },
  {
    id: '5',
    name: '송파 Dunk',
    shortName: 'SD',
    region: '송파구 잠실',
    level: 'A',
    matchScore: 90,
    memberCount: 8,
    maxMembers: 10,
    isOfficial: true,
    captainId: 'user5',
    description: '잠실 코트에서 주로 활동합니다.',
    totalGames: 22,
    aiReports: 18,
    activeDays: 55,
  },
  {
    id: '9',
    name: '동작 Phoenix',
    shortName: 'DP',
    region: '동작구 사당',
    level: 'A+',
    matchScore: 93,
    memberCount: 5,
    maxMembers: 10,
    isOfficial: true,
    captainId: 'user9',
    description: '실력 향상을 목표로 하는 팀입니다.',
    totalGames: 28,
    aiReports: 22,
    activeDays: 70,
  },
  {
    id: '10',
    name: '서초 Lions',
    shortName: 'SL',
    region: '서초구 방배',
    level: 'A',
    matchScore: 87,
    memberCount: 9,
    maxMembers: 10,
    isOfficial: true,
    captainId: 'user10',
    description: '주말 위주로 활동하는 팀입니다.',
    totalGames: 16,
    aiReports: 13,
    activeDays: 45,
  },
]

// 내 팀 정보
export const mockMyTeam: Team = {
  id: '1',
  name: '세종 born',
  shortName: 'SB',
  memberCount: 6,
  maxMembers: 10,
  level: 'A',
  region: '광진구 능동',
  totalGames: 18,
  aiReports: 14,
  activeDays: 45,
  isOfficial: true,
  captainId: 'user1',
  description: '세종대 기반 농구 동호회',
}
